### ISSUE TITLE
Authentication error with ring while running container

### ISSUE THREAD

**Issue by sanzgiri** [mdnahian/ring-gdrive#3]
I get the following error while running the container:

```
Traceback (most recent call last):
  File "/opt/ring/app/monitor/run.py", line 49, in <module>
    ring_service = ring.RingDoorbell(const.RING_EMAIL, const.RING_PASS)
  File "/opt/ring/app/monitor/ring.py", line 11, in __init__
    self.session = Ring(username, password)
  File "/usr/local/lib/python3.6/site-packages/ring_doorbell/__init__.py", line 54, in __init__
    self._process_cached_session()
  File "/usr/local/lib/python3.6/site-packages/ring_doorbell/__init__.py", line 87, in _process_cached_session
    self._authenticate()
  File "/usr/local/lib/python3.6/site-packages/ring_doorbell/__init__.py", line 155, in _authenticate
    req.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.ring.com/clients_api/session
```

I am providing the correct EMAIL and PASSWORD. Does something else have to be enabled on the RING side?

I have obtained the refresh token as described here: https://github.com/dgreif/ring/wiki/Refresh-Tokens
Does this need to be provided somehow?

**Comment by sanzgiri** [comment]
Looks like you cannot access videos without an active subscription. That might be what's causing the error.
